- name: Daemon Reload
  ansible.builtin.systemd:
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"

- name: Restart Grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted
  when: ansible_service_mgr == "systemd"

- name: Restart Loki
  ansible.builtin.service:
    name: loki
    state: restarted
  when: ansible_service_mgr == "systemd"

- name: Restart Tempo
  ansible.builtin.service:
    name: tempo
    state: restarted
  when: ansible_service_mgr == "systemd"
