- name: Create prometheus user
  ansible.builtin.user:
    name: prometheus
    shell: /bin/false
    create_home: no

- name: Create necessary directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download and extract Prometheus
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prom_version }}/prometheus-{{ prom_version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: yes
    creates: /tmp/prometheus-{{ prom_version }}.linux-amd64/prometheus

- name: Copy Prometheus binaries
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prom_version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: prometheus
    group: prometheus
    mode: '0755'
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Remove Prometheus temp directory
  ansible.builtin.file:
    path: "/tmp/prometheus-{{ prom_version }}.linux-amd64"
    state: absent

- name: Copy Prometheus configuration file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
  notify: Reload Prometheus

- name: Copy Alerting Rules file
  ansible.builtin.template:
    src: alert_rules.yml.j2
    dest: /etc/prometheus/alert_rules.yml
    owner: prometheus
    group: prometheus
  notify: Reload Prometheus

- name: Copy Prometheus Systemd service file
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: Daemon Reload

- name: Ensure Prometheus service is running
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes
